export const carsData=[
    {
      id: '1',
      name: 'Toyota Camry',
      brand: 'Toyota',
      price: 26000,
      fuelType: 'Petrol',
      seatingCapacity: 5,
      year: 2023,
      image: '/api/placeholder/400/300?text=Toyota+Camry',
      engine: '2.5L 4-Cylinder',
      transmission: 'Automatic',
      features: [
        'Power Steering',
        'Anti-lock Braking System',
        'Driver & Passenger Airbags',
        'Air Conditioning',
        'Power Windows',
        'Central Locking',
        'Keyless Entry',
        'Touchscreen Infotainment',
        'Bluetooth Connectivity',
        'Rear Parking Sensors'
      ]
    },
  {
    id: '2',
    name: 'Honda Accord',
    brand: 'Honda',
    price: 28000,
    fuelType: 'Petrol',
    seatingCapacity: 5,
    year: 2023,
    image: '/api/placeholder/400/300?text=Honda+Accord',
    engine: '1.5L Turbo',
    transmission: 'CVT',
    features: [
      'Power Steering',
      'Anti-lock Braking System',
      'Multiple Airbags',
      'Dual-Zone Climate Control',
      'Power Windows',
      'Central Locking',
      'Keyless Entry',
      'Apple CarPlay & Android Auto',
      'Bluetooth Connectivity',
      'Parking Camera'
    ]
  },
  {
    id: '3',
    name: 'BMW 3 Series',
    brand: 'BMW',
    price: 45000,
    fuelType: 'Petrol',
    seatingCapacity: 5,
    year: 2023,
    image: '/api/placeholder/400/300?text=BMW+3+Series',
    engine: '2.0L TwinPower Turbo',
    transmission: '8-Speed Automatic',
    features: [
      'Power Steering',
      'Dynamic Stability Control',
      'Six Airbags',
      'Climate Control',
      'Power Windows',
      'Central Locking',
      'Keyless Entry',
      'iDrive Infotainment System',
      'Bluetooth Connectivity',
      'Parking Sensors & Camera'
    ]
  },
  {
    id: '4',
    name: 'Mercedes-Benz C-Class',
    brand: 'Mercedes',
    price: 48000,
    fuelType: 'Petrol',
    seatingCapacity: 5,
    year: 2023,
    image: '/api/placeholder/400/300?text=Mercedes+C-Class',
    engine: '2.0L Turbocharged',
    transmission: '9-Speed Automatic',
    features: [
      'Power Steering',
      'Electronic Stability Program',
      'Multiple Airbags',
      'Dual-Zone Climate Control',
      'Power Windows',
      'Central Locking',
      'Keyless Go',
      'MBUX Infotainment System',
      'Bluetooth Connectivity',
      'Active Parking Assist'
    ]
  },
  {
    id: '5',
    name: 'Ford Mustang',
    brand: 'Ford',
    price: 39000,
    fuelType: 'Petrol',
    seatingCapacity: 4,
    year: 2023,
    image: '/api/placeholder/400/300?text=Ford+Mustang',
    engine: '5.0L V8',
    transmission: '10-Speed Automatic',
    features: [
      'Power Steering',
      'Electronic Stability Control',
      'Front & Side Airbags',
      'Climate Control',
      'Power Windows',
      'Central Locking',
      'Keyless Entry',
      'SYNC Infotainment System',
      'Bluetooth Connectivity',
      'Rear View Camera'
    ]
  },
  {
    id: '6',
    name: 'Audi A4',
    brand: 'Audi',
    price: 42000,
    fuelType: 'Petrol',
    seatingCapacity: 5,
    year: 2023,
    image: '/api/placeholder/400/300?text=Audi+A4',
    engine: '2.0L TFSI',
    transmission: '7-Speed S tronic',
    features: [
      'Power Steering',
      'Electronic Stability Control',
      'Multiple Airbags',
      'Three-Zone Climate Control',
      'Power Windows',
      'Central Locking',
      'Keyless Go',
      'MMI Infotainment System',
      'Bluetooth Connectivity',
      'Parking System Plus'
    ]
  },
  {
    id: '7',
    name: 'Tesla Model 3',
    brand: 'Tesla',
    price: 49000,
    fuelType: 'Electric',
    seatingCapacity: 5,
    year: 2023,
    image: '/api/placeholder/400/300?text=Tesla+Model+3',
    engine: 'Dual Motor Electric',
    transmission: 'Single-Speed',
    features: [
      'Autopilot',
      'Full Self-Driving Capability',
      'Multiple Airbags',
      'Climate Control',
      'Power Windows',
      'Keyless Entry',
      '15" Touchscreen Display',
      'Premium Audio System',
      'Bluetooth Connectivity',
      'Surround View Cameras'
    ]
  },
  {
    id: '8',
    name: 'Hyundai Sonata',
    brand: 'Hyundai',
    price: 27000,
    fuelType: 'Petrol',
    seatingCapacity: 5,
    year: 2023,
    image: '/api/placeholder/400/300?text=Hyundai+Sonata',
    engine: '2.5L 4-Cylinder',
    transmission: '8-Speed Automatic',
    features: [
      'Power Steering',
      'Electronic Stability Control',
      'Six Airbags',
      'Dual-Zone Climate Control',
      'Power Windows',
      'Central Locking',
      'Smart Key with Push Button Start',
      '8" Touchscreen Display',
      'Apple CarPlay & Android Auto',
      'Rear View Camera'
    ]
  },
  {
    id: '9',
    name: 'Kia K5',
    brand: 'Kia',
    price: 25000,
    fuelType: 'Petrol',
    seatingCapacity: 5,
    year: 2023,
    image: '/api/placeholder/400/300?text=Kia+K5',
    engine: '1.6L Turbocharged',
    transmission: '8-Speed Automatic',
    features: [
      'Power Steering',
      'Electronic Stability Control',
      'Multiple Airbags',
      'Dual-Zone Climate Control',
      'Power Windows',
      'Central Locking',
      'Smart Key with Push Button Start',
      '8" Touchscreen Display',
      'Apple CarPlay & Android Auto',
      'Rear View Camera'
    ]
  },
  {
    id: '10',
    name: 'Volkswagen Golf',
    brand: 'Volkswagen',
    price: 24000,
    fuelType: 'Petrol',
    seatingCapacity: 5,
    year: 2023,
    image: '/api/placeholder/400/300?text=VW+Golf',
    engine: '1.4L TSI',
    transmission: '8-Speed Automatic',
    features: [
      'Power Steering',
      'Electronic Stability Control',
      'Six Airbags',
      'Climate Control',
      'Power Windows',
      'Central Locking',
      'Keyless Access',
      '8.25" Touchscreen Display',
      'App-Connect',
      'Rear View Camera'
    ]
  },
  {
    id: '11',
    name: 'Toyota Prius',
    brand: 'Toyota',
    price: 29000,
    fuelType: 'Hybrid',
    seatingCapacity: 5,
    year: 2023,
    image: '/api/placeholder/400/300?text=Toyota+Prius',
    engine: '1.8L Hybrid',
    transmission: 'CVT',
    features: [
      'Power Steering',
      'Vehicle Stability Control',
      'Multiple Airbags',
      'Climate Control',
      'Power Windows',
      'Central Locking',
      'Smart Key System',
      '7" Touchscreen Display',
      'Apple CarPlay & Android Auto',
      'Backup Camera'
    ]
  },
  {
    id: '12',
    name: 'Honda CR-V',
    brand: 'Honda',
    price: 32000,
    fuelType: 'Petrol',
    seatingCapacity: 5,
    year: 2023,
    image: '/api/placeholder/400/300?text=Honda+CR-V',
    engine: '1.5L Turbocharged',
    transmission: 'CVT',
    features: [
      'Power Steering',
      'Vehicle Stability Assist',
      'Multiple Airbags',
      'Dual-Zone Climate Control',
      'Power Windows',
      'Central Locking',
      'Smart Entry with Push Button Start',
      '7" Touchscreen Display',
      'Apple CarPlay & Android Auto',
      'Multi-Angle Rearview Camera'
    ]
  },
  {
    id: '13',
    name: 'BMW X5',
    brand: 'BMW',
    price: 65000,
    fuelType: 'Diesel',
    seatingCapacity: 7,
    year: 2023,
    image: '/api/placeholder/400/300?text=BMW+X5',
    engine: '3.0L TwinPower Turbo',
    transmission: '8-Speed Automatic',
    features: [
      'Power Steering',
      'Dynamic Stability Control',
      'Multiple Airbags',
      'Four-Zone Climate Control',
      'Power Windows',
      'Central Locking',
      'Comfort Access',
      '12.3" Touchscreen Display',
      'Harman Kardon Surround Sound System',
      'Parking Assistant Plus'
    ]
  },
  {
    id: '14',
    name: 'Mercedes-Benz GLE',
    brand: 'Mercedes',
    price: 68000,
    fuelType: 'Diesel',
    seatingCapacity: 7,
    year: 2023,
    image: '/api/placeholder/400/300?text=Mercedes+GLE',
    engine: '3.0L Inline-6 Turbocharged',
    transmission: '9-Speed Automatic',
    features: [
      'Power Steering',
      'Electronic Stability Program',
      'Multiple Airbags',
      'Four-Zone Climate Control',
      'Power Windows',
      'Central Locking',
      'KEYLESS-GO',
      '12.3" Touchscreen Display',
      'Burmester Surround Sound System',
      'Active Parking Assist'
    ]
  },
  {
    id: '15',
    name: 'Ford F-150',
    brand: 'Ford',
    price: 45000,
    fuelType: 'Petrol',
    seatingCapacity: 6,
    year: 2023,
    image: '/api/placeholder/400/300?text=Ford+F-150',
    engine: '3.5L EcoBoost V6',
    transmission: '10-Speed Automatic',
    features: [
      'Power Steering',
      'AdvanceTrac with Roll Stability Control',
      'Multiple Airbags',
      'Dual-Zone Climate Control',
      'Power Windows',
      'Central Locking',
      'Intelligent Access with Push Button Start',
      '12" Touchscreen Display',
      'B&O Sound System',
      '360-Degree Camera'
    ]
  },
  {
    id: '16',
    name: 'Audi Q7',
    brand: 'Audi',
    price: 69000,
    fuelType: 'Diesel',
    seatingCapacity: 7,
    year: 2023,
    image: '/api/placeholder/400/300?text=Audi+Q7',
    engine: '3.0L TFSI V6',
    transmission: '8-Speed Tiptronic',
    features: [
      'Power Steering',
      'Electronic Stability Control',
      'Multiple Airbags',
      'Four-Zone Climate Control',
      'Power Windows',
      'Central Locking',
      'Advanced Key',
      '10.1" Touchscreen Display',
      'Bang & Olufsen 3D Premium Sound System',
      'Park Assist with 360-Degree Camera'
    ]
  },
  {
    id: '17',
    name: 'Tesla Model Y',
    brand: 'Tesla',
    price: 56000,
    fuelType: 'Electric',
    seatingCapacity: 5,
    year: 2023,
    image: '/api/placeholder/400/300?text=Tesla+Model+Y',
    engine: 'Dual Motor Electric',
    transmission: 'Single-Speed',
    features: [
      'Autopilot',
      'Full Self-Driving Capability',
      'Multiple Airbags',
      'Climate Control',
      'Power Windows',
      'Keyless Entry',
      '15" Touchscreen Display',
      'Premium Audio System',
      'Bluetooth Connectivity',
      'Surround View Cameras'
    ]
  },
  {
    id: '18',
    name: 'Hyundai Santa Fe',
    brand: 'Hyundai',
    price: 36000,
    fuelType: 'Diesel',
    seatingCapacity: 7,
    year: 2023,
    image: '/api/placeholder/400/300?text=Hyundai+Santa+Fe',
    engine: '2.2L CRDi',
    transmission: '8-Speed Automatic',
    features: [
      'Power Steering',
      'Electronic Stability Control',
      'Six Airbags',
      'Dual-Zone Climate Control',
      'Power Windows',
      'Central Locking',
      'Smart Key with Push Button Start',
      '10.25" Touchscreen Display',
      'Harman Kardon Premium Audio',
      'Surround View Monitor'
    ]
  },
  {
    id: '19',
    name: 'Kia Sorento',
    brand: 'Kia',
    price: 35000,
    fuelType: 'Diesel',
    seatingCapacity: 7,
    year: 2023,
    image: '/api/placeholder/400/300?text=Kia+Sorento',
    engine: '2.2L CRDi',
    transmission: '8-Speed Automatic',
    features: [
      'Power Steering',
      'Electronic Stability Control',
      'Multiple Airbags',
      'Tri-Zone Climate Control',
      'Power Windows',
      'Central Locking',
      'Smart Key with Push Button Start',
      '10.25" Touchscreen Display',
      'Bose Premium Audio',
      '360-Degree Camera'
    ]
  },
  {
    id: '20',
    name: 'Volkswagen Tiguan',
    brand: 'Volkswagen',
    price: 33000,
    fuelType: 'Petrol',
    seatingCapacity: 5,
    year: 2023,
    image: '/api/placeholder/400/300?text=VW+Tiguan',
    engine: '2.0L TSI',
    transmission: '8-Speed Automatic',
    features: [
      'Power Steering',
      'Electronic Stability Control',
      'Six Airbags',
      'Three-Zone Climate Control',
      'Power Windows',
      'Central Locking',
      'Keyless Access',
      '8" Touchscreen Display',
      'Fender Premium Audio System',
      'Area View Camera'
    ]
  }
];

